@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 20

title VON-Connector
scale 0.9


box "Trust Anchor" #LightBlue
participant "Trust Anchor" as TA
actor "Agent" as Ag
endbox

participant "Ledger" as Ledger
participant "Issuer" as I
actor "User" as User


note over User
  what is a user?

endnote



=== BOOTSTRAP - from ZERO to HERO ==
User -> TA
TA -> Ledger: Look up own nym
TA -[#blue]>: <nym>





=== more processes ==
note over TA, Ledger
    <font color=red>THIS is ROUGH - as rough as it gets</font>

endnote
@enduml